import React, { useState } from 'react'
import { motion, AnimatePresence } from 'framer-motion'
import { Terminal, Code, Play, Trash2, Copy, Download } from 'lucide-react'
import { useAI } from '../context/AIContext'
import { Prism as SyntaxHighlighter } from 'react-syntax-highlighter'
import { tomorrow } from 'react-syntax-highlighter/dist/esm/styles/prism'
import toast from 'react-hot-toast'

const CodeOutput: React.FC = () => {
  const { state, dispatch } = useAI()
  const [activeTab, setActiveTab] = useState<'output' | 'code'>('output')

  const handleClearOutput = () => {
    dispatch({ type: 'CLEAR_OUTPUT' })
    toast.success('Output cleared!')
  }

  const handleCopyCode = () => {
    if (state.currentProject) {
      const code = generatePythonCode(state.currentProject.blocks)
      navigator.clipboard.writeText(code)
      toast.success('Code copied to clipboard!')
    }
  }

  const handleDownloadCode = () => {
    if (state.currentProject) {
      const code = generatePythonCode(state.currentProject.blocks)
      const blob = new Blob([code], { type: 'text/plain' })
      const url = URL.createObjectURL(blob)
      const link = document.createElement('a')
      link.href = url
      link.download = `${state.currentProject.name}.py`
      link.click()
      URL.revokeObjectURL(url)
      toast.success('Code downloaded!')
    }
  }

  const generatePythonCode = (blocks: any[]) => {
    let code = `# AI Project: ${state.currentProject?.name || 'Untitled'}
# Generated by AI Block Coding

import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
import matplotlib.pyplot as plt
import seaborn as sns

# AI Project Code
print("Starting AI Project...")

`
    
    blocks.forEach((block, index) => {
      code += `# ${block.title}
${block.code}
print(f"Step ${index + 1}: ${block.title} completed")

`
    })
    
    code += `print("AI Project completed successfully!")`
    return code
  }

  return (
    <div className="h-full flex flex-col">
      {/* Tab Header */}
      <div className="bg-gray-800 border-b border-gray-700 flex items-center justify-between">
        <div className="flex">
          <button
            onClick={() => setActiveTab('output')}
            className={`px-4 py-2 flex items-center space-x-2 text-sm font-medium transition-colors ${
              activeTab === 'output'
                ? 'text-white border-b-2 border-green-400'
                : 'text-gray-400 hover:text-white'
            }`}
          >
            <Terminal className="w-4 h-4" />
            <span>Output</span>
          </button>
          
          <button
            onClick={() => setActiveTab('code')}
            className={`px-4 py-2 flex items-center space-x-2 text-sm font-medium transition-colors ${
              activeTab === 'code'
                ? 'text-white border-b-2 border-green-400'
                : 'text-gray-400 hover:text-white'
            }`}
          >
            <Code className="w-4 h-4" />
            <span>Generated Code</span>
          </button>
        </div>

        <div className="flex items-center space-x-2 pr-4">
          {activeTab === 'output' && (
            <button
              onClick={handleClearOutput}
              className="p-2 text-gray-400 hover:text-white transition-colors"
              title="Clear Output"
            >
              <Trash2 className="w-4 h-4" />
            </button>
          )}
          
          {activeTab === 'code' && (
            <>
              <button
                onClick={handleCopyCode}
                className="p-2 text-gray-400 hover:text-white transition-colors"
                title="Copy Code"
              >
                <Copy className="w-4 h-4" />
              </button>
              
              <button
                onClick={handleDownloadCode}
                className="p-2 text-gray-400 hover:text-white transition-colors"
                title="Download Code"
              >
                <Download className="w-4 h-4" />
              </button>
            </>
          )}
        </div>
      </div>

      {/* Tab Content */}
      <div className="flex-1 overflow-hidden">
        <AnimatePresence mode="wait">
          {activeTab === 'output' && (
            <motion.div
              key="output"
              initial={{ opacity: 0, x: 20 }}
              animate={{ opacity: 1, x: 0 }}
              exit={{ opacity: 0, x: -20 }}
              transition={{ duration: 0.2 }}
              className="h-full p-4 overflow-y-auto"
            >
              {state.output.length === 0 ? (
                <div className="h-full flex items-center justify-center text-gray-500">
                  <div className="text-center">
                    <Terminal className="w-12 h-12 mx-auto mb-4 opacity-50" />
                    <h3 className="text-lg font-semibold mb-2">No Output Yet</h3>
                    <p className="text-sm">
                      Run your AI project to see the output here
                    </p>
                  </div>
                </div>
              ) : (
                <div className="space-y-2">
                  {state.output.map((line, index) => (
                    <motion.div
                      key={index}
                      initial={{ opacity: 0, y: 10 }}
                      animate={{ opacity: 1, y: 0 }}
                      transition={{ delay: index * 0.1 }}
                      className="flex items-start space-x-2"
                    >
                      <span className="text-green-400 font-mono text-sm">
                        {index + 1 > 9 ? index + 1 : `0${index + 1}`}
                      </span>
                      <span className="text-green-400 font-mono text-sm">{'>'}</span>
                      <span className="text-white font-mono text-sm">{line}</span>
                    </motion.div>
                  ))}
                  
                  {state.isRunning && (
                    <motion.div
                      initial={{ opacity: 0 }}
                      animate={{ opacity: 1 }}
                      className="flex items-center space-x-2 text-yellow-400"
                    >
                      <div className="w-2 h-2 bg-yellow-400 rounded-full animate-pulse" />
                      <span className="text-sm">Running...</span>
                    </motion.div>
                  )}
                </div>
              )}
            </motion.div>
          )}

          {activeTab === 'code' && (
            <motion.div
              key="code"
              initial={{ opacity: 0, x: 20 }}
              animate={{ opacity: 1, x: 0 }}
              exit={{ opacity: 0, x: -20 }}
              transition={{ duration: 0.2 }}
              className="h-full overflow-y-auto"
            >
              {!state.currentProject || state.currentProject.blocks.length === 0 ? (
                <div className="h-full flex items-center justify-center text-gray-500">
                  <div className="text-center">
                    <Code className="w-12 h-12 mx-auto mb-4 opacity-50" />
                    <h3 className="text-lg font-semibold mb-2">No Code Generated</h3>
                    <p className="text-sm">
                      Add AI blocks to your project to generate Python code
                    </p>
                  </div>
                </div>
              ) : (
                <div className="p-4">
                  <SyntaxHighlighter
                    language="python"
                    style={tomorrow}
                    customStyle={{
                      margin: 0,
                      borderRadius: '8px',
                      fontSize: '14px',
                      lineHeight: '1.5'
                    }}
                  >
                    {generatePythonCode(state.currentProject.blocks)}
                  </SyntaxHighlighter>
                </div>
              )}
            </motion.div>
          )}
        </AnimatePresence>
      </div>
    </div>
  )
}

export default CodeOutput 